# Version Info
version = '0.15.0'

# General
run_analysis = false                                                              # true or false. Can skip this step if json files have already been created.
run_plotting = true                                                               # true or false.
run_statistics = false                                                            # true or false.
verbose = true                                                                    # true or false.
verbose_cmd_line_args = false                                                     # true or false.
multicore_processing = true                                                       # true or false. Use multicore processing during analysis? Multicore processing currently works within participants not between them. Recommended: true
max_core_usage = 'max'                                                            # 'max' to select number of cores available on the system, alternatively an int to manually select number of cores to use. Recommended: 'max' Options: ['max', 6, 5, 4, 3, 2, 1].
brain_file_loc = ''                                                               # Either the absolute location of brain files or blank, if blank then a browser window will allow you to search for the files at runtime. If passing in this information as a command line flag, this will be ignored.
report_output_folder = ''                                                         # Either the absolute location of json files or blank, if blank then a browser window will allow you to search for the files at runtime. If passing in this information as a command line flag, this will be ignored.
file_cleanup = 'move'                                                             # Move or delete intermediate files. Options: ['move', 'delete'].

# Analysis
atlas_number = 'HarvardOxford-sub'                                                #  Options: ['Cerebellum-MNIflirt', 'Cerebellum-MNIfnirt', 'HarvardOxford-cort', 'HarvardOxford-sub', 'JHU-ICBM-labels', 'JHU-ICBM-tracts', 'juelich', 'MNI', 'SMATT-labels', 'STN', 'striatum-structural', 'Talairach-labels', 'Thalamus'].
output_folder = 'DEFAULT'                                                         # Directory to save output. If set to DEFAULT, output directory will be set to the cortical atlas used appended with "_ROI_report".  Example: HarvardOxford-Cortical_ROI_report/
dof = 12                                                                          # Degrees of freedom for FLIRT. Recommended: 12
anat_align = false                                                                # true or false. Recommended: true.
grey_matter_segment = false                                                       # true or false. Recommended: true.  Note: Requires anatomical align be true to function.
fslfast_min_prob = 0.1                                                            # Recommended: 0.1
noise_cutoff = false                                                              # true or false. Recommended: true.
stat_map_folder = 'QA_report/'                                                    # Folder name which contains the statistical map files. Example: QA_report/
stat_map_suffix = '_tSNR.img'                                                     # File name suffix of the statistical map files. Include the file extension. Example: _tSNR.img
conf_level_number = '99%, 2.58'                                                   # Set the confidence level for confidence interval calculations. Numbers represent the confidence level and the corresponding critical z value. Recommended: 95%, 1.96. Options: ['80%, 1.28', '85%, 1.44', '90%, 1.64', '95%, 1.96', '98%, 2.33', '99%, 2.58'].
binary_params = ['']                                                              # Add parameters here which will either be on or off.

# Parsing
parameter_dict1 = ['Hyperband', 'Inplane Acceleration']                           # Comma-separated list of parameter names to be parsed for and plotted.   As these critical parameters will also be used when labelling the rows and columns of both the violin plots and histograms, they should be written as you want them to appear in these figures.
parameter_dict2 = ['hb', 'ip']                                                    # Comma-separated list of terms to parse the file name for. Each entry corresponds to a critical parameter above.  Optional if using table parameter verification, however if the file name contains this information it can use this information to auto-detect the critical parameters used for each fMRI volume.

# Plotting
plot_dpi = 200                                                                    # Recommended value 600
plot_font_size = 40                                                               # Recommended value 30
plot_scale = 10                                                                   # Recommended value 10
make_violin_plot = false                                                          # True or False.
make_brain_table = true                                                           # True or False.
make_one_region_fig = false                                                       # True or False.
make_histogram = false                                                            # True or False.
colorblind_friendly_plot_colours = ['#ffeda0', '#feb24c', '#fc4e2a', '#bd0026']   # Hex values of colourblind friendly colour scale.
regional_fig_rois = [1, 2, 3, 4]                                                  # Provide a comma-separated list of regions to plot e.g. [3, 5], the string 'all' for all rois or the string 'Runtime' to provide regions at runtime.

# Violin_plot
table_x_label = 'tSNR mean'                                                       # 
table_y_label = 'ROI'                                                             # 
violin_show_data = true                                                           # True or False.
violin_jitter = true                                                              # True or False.
violin_colour = '#fc4e2a'                                                         # Hex value of colour blind friendly colour. Value taken from colorblind friendly plot colours.
boxplot_colour = '#feb24c'                                                        # Hex value of colour blind friendly colour. Value taken from colorblind friendly plot colours.
table_cols = 'Hyperband'                                                          # 
table_rows = 'Inplane Acceleration'                                               # 

# Brain_table
brain_tight_layout = false                                                        # True or False. Use a tight layout when laying out the figure. Recommended: false
brain_fig_value_min = 0                                                           # Provides the minimum value of the colourbar when creating mean and median images. For example, set minimum to 50 to make areas with values below 50 appear black. Recommended value: 0
brain_fig_value_max = 90                                                          # Provides the maximum value of the colourbar when creating mean and median images. For example, set maximum to 50 to make areas with values above 50 appear as the brighest colour on the colourbar. Recommended value: None. Note: will default to 100 for scaled maps.
brain_x_coord = 91                                                                # Voxel location to slice the images at in the x axis. Recommended settings for both variables: 91 or 58
brain_z_coord = 91                                                                # Voxel location to slice the images at in the z axis. Recommended settings for both variables: 91 or 58
brain_table_col_labels = 'MB'                                                     # Label for columns.
brain_table_row_labels = 'SENSE'                                                  # Label for rows.
brain_table_cols = 'Hyperband'                                                    # 
brain_table_rows = 'Inplane Acceleration'                                         # 

# Region_barchart
single_roi_fig_label_x = 'Multiband factor'                                       # 
single_roi_fig_label_y = 'temporal Signal to Noise Ratio'                         # 
single_roi_fig_label_fill = 'SENSE factor'                                        # 
single_roi_fig_x_axis = 'Hyperband'                                               # 
single_roi_fig_colour = 'Inplane Acceleration'                                    # 

# Region_histogram
histogram_binwidth = 5                                                            # 
histogram_fig_label_x = 'temporal Signal to Noise Ratio'                          # 
histogram_fig_label_y = 'Frequency'                                               # 
histogram_stat_line_size = 1.5                                                    # 
histogram_show_mean = true                                                        # True or False.
histogram_show_median = true                                                      # True or False.
histogram_show_legend = true                                                      # True or False.
histogram_fig_x_facet = 'Hyperband'                                               # 
histogram_fig_y_facet = 'Inplane Acceleration'                                    # 
histogram_fig_colour = '#fc4e2a'                                                  # Hex value of colour blind friendly colour. Value taken from colorblind friendly plot colours.

